import { readFileSync } from "node:fs";
import { parse } from "yaml";
import { describe, expect, it } from "vitest";
import { generateDependabotConfig, parsePolicy, type Policy } from "../src/index.ts";

const examplePath = new URL("../examples/depbot.policy.yml", import.meta.url);

function policyFrom(source: string): Policy {
  const result = parsePolicy(source);
  if (!result.ok) throw new Error(`invalid test policy: ${JSON.stringify(result.errors)}`);
  return result.policy;
}

describe("generateDependabotConfig: snapshots", () => {
  it("example policy", async () => {
    const output = generateDependabotConfig(policyFrom(readFileSync(examplePath, "utf8")));

    await expect(output).toMatchFileSnapshot("__snapshots__/example.dependabot.yml");
  });

  it("minimal policy", async () => {
    const output = generateDependabotConfig(
      policyFrom("version: 1\necosystems: [{ type: npm, directory: / }]"),
    );

    await expect(output).toMatchFileSnapshot("__snapshots__/minimal.dependabot.yml");
  });
});

describe("generateDependabotConfig: content", () => {
  it("maps each ecosystem to an update entry", () => {
    const policy = policyFrom(`
version: 1
ecosystems:
  - { type: npm, directory: /web, schedule: daily }
  - { type: docker, directory: /, schedule: monthly }
`);

    expect(parse(generateDependabotConfig(policy))).toEqual({
      version: 2,
      updates: [
        { "package-ecosystem": "npm", directory: "/web", schedule: { interval: "daily" } },
        { "package-ecosystem": "docker", directory: "/", schedule: { interval: "monthly" } },
      ],
    });
  });

  it("ignores an unscoped block entry in every ecosystem", () => {
    const policy = policyFrom(`
version: 1
ecosystems: [{ type: npm, directory: / }, { type: pip, directory: /api }]
block: [{ name: left-pad, reason: Unmaintained }]
`);

    const { updates } = parse(generateDependabotConfig(policy));

    expect(updates.map((update: { ignore?: unknown }) => update.ignore)).toEqual([
      [{ "dependency-name": "left-pad" }],
      [{ "dependency-name": "left-pad" }],
    ]);
  });

  it("ignores a scoped block entry only in its ecosystems", () => {
    const policy = policyFrom(`
version: 1
ecosystems: [{ type: npm, directory: / }, { type: github-actions, directory: / }]
block: [{ name: react, reason: Pinned, ecosystems: [npm] }]
`);

    const { updates } = parse(generateDependabotConfig(policy));

    expect(updates[0].ignore).toEqual([{ "dependency-name": "react" }]);
    expect(updates[1]).not.toHaveProperty("ignore");
  });

  it("applies a scoped block entry to every directory of that ecosystem", () => {
    const policy = policyFrom(`
version: 1
ecosystems: [{ type: npm, directory: / }, { type: npm, directory: /web }]
block: [{ name: react, reason: Pinned, ecosystems: [npm] }]
`);

    const { updates } = parse(generateDependabotConfig(policy));

    expect(updates.every((update: { ignore?: unknown }) => update.ignore !== undefined)).toBe(true);
  });

  it("keeps each block reason as a comment on one line", () => {
    const policy = policyFrom(`
version: 1
ecosystems: [{ type: npm, directory: / }]
block:
  - name: react
    reason: |
      Pinned until the
      React 19 migration
`);

    const output = generateDependabotConfig(policy);

    expect(output).toContain("- dependency-name: react # Pinned until the React 19 migration\n");
    expect(parse(output).updates[0].ignore).toEqual([{ "dependency-name": "react" }]);
  });

  it("starts with a do-not-edit header", () => {
    const output = generateDependabotConfig(
      policyFrom("version: 1\necosystems: [{ type: npm, directory: / }]"),
    );

    expect(output.startsWith("# Generated by depbot-policy")).toBe(true);
  });
});
