import { Document, isScalar } from "yaml";
import type { Policy } from "./schema.js";

type Ecosystem = Policy["ecosystems"][number];
type BlockEntry = Policy["block"][number];

const header = [
  " Generated by depbot-policy from depbot.policy.yml. Do not edit by hand:",
  " change the policy file and regenerate.",
].join("\n");

/**
 * Builds the contents of `.github/dependabot.yml` for a validated policy.
 *
 * Blocked packages become `ignore` entries, with each reason kept as a trailing comment.
 */
export function generateDependabotConfig(policy: Policy): string {
  const updates = policy.ecosystems.map((ecosystem) => ({
    ecosystem,
    blocked: policy.block.filter((entry) => appliesTo(entry, ecosystem)),
  }));

  const doc = new Document({
    version: 2,
    updates: updates.map(({ ecosystem, blocked }) => ({
      "package-ecosystem": ecosystem.type,
      directory: ecosystem.directory,
      schedule: { interval: ecosystem.schedule },
      ...(blocked.length > 0 && {
        ignore: blocked.map((entry) => ({ "dependency-name": entry.name })),
      }),
    })),
  });
  doc.commentBefore = header;

  updates.forEach(({ blocked }, updateIndex) => {
    blocked.forEach((entry, ignoreIndex) => {
      const name = doc.getIn(["updates", updateIndex, "ignore", ignoreIndex, "dependency-name"], true);
      // A trailing comment must stay on one line, or the rest of the reason becomes YAML.
      if (isScalar(name)) name.comment = ` ${entry.reason.replace(/\s+/g, " ").trim()}`;
    });
  });

  return doc.toString({ lineWidth: 0 });
}

function appliesTo(entry: BlockEntry, ecosystem: Ecosystem): boolean {
  return entry.ecosystems === undefined || entry.ecosystems.includes(ecosystem.type);
}
