import { Document, isScalar } from "yaml";
import { reviewerScript } from "./rotation.ts";
import type { Policy } from "./schema.ts";

type AutoMerge = Policy["autoMerge"];

// Pinned to a commit, not a tag, because a tag can be moved to point at different code.
// Bump both values by hand when fetch-metadata releases. In generated workflows, the version
// comment lets Dependabot's github-actions ecosystem keep the pin current.
const fetchMetadata = {
  action: "dependabot/fetch-metadata@25dd0e34f4fe68f24cc83900b1fe3fe149efef98",
  version: "v3.1.0",
};

const header = [
  " Generated by depbot-policy from depbot.policy.yml. Do not edit by hand:",
  " change the policy file and regenerate.",
  "",
  " Requires, in the repository settings:",
  " - \"Allow auto-merge\" enabled.",
  " - Branch protection on the default branch with required status checks.",
  "   Without required checks, GitHub merges at once instead of waiting for CI.",
].join("\n");

const updateTypeValues: Record<AutoMerge["updateTypes"][number], string> = {
  patch: "version-update:semver-patch",
  minor: "version-update:semver-minor",
};

const dependencyTypeValues: Record<AutoMerge["dependencyTypes"][number], string> = {
  development: "direct:development",
  production: "direct:production",
};

/**
 * Builds `.github/workflows/dependabot-auto-merge.yml`: a workflow that enables auto-merge on
 * Dependabot pull requests the policy allows. Everything else is left for a human to review and,
 * with a review rotation, assigned to this week's reviewer.
 */
export function generateAutoMergeWorkflow(policy: Policy): string {
  const { updateTypes, dependencyTypes, mergeMethod } = policy.autoMerge;
  const prEnv = {
    PR_URL: "${{ github.event.pull_request.html_url }}",
    GH_TOKEN: "${{ secrets.GITHUB_TOKEN }}",
  };

  const doc = new Document({
    name: "Dependabot auto-merge",
    on: "pull_request",
    permissions: { contents: "write", "pull-requests": "write" },
    jobs: {
      "auto-merge": {
        "runs-on": "ubuntu-latest",
        // Both checks: the PR was opened by Dependabot and this run was triggered by Dependabot,
        // so a commit someone else pushes to a Dependabot branch is never auto-merged.
        if: "github.event.pull_request.user.login == 'dependabot[bot]' && github.actor == 'dependabot[bot]'",
        steps: [
          {
            id: "metadata",
            uses: fetchMetadata.action,
            with: { "github-token": "${{ secrets.GITHUB_TOKEN }}" },
          },
          {
            id: "auto-merge",
            name: "Enable auto-merge",
            if: allOf([
              anyOf("steps.metadata.outputs.update-type", updateTypes.map((type) => updateTypeValues[type])),
              anyOf(
                "steps.metadata.outputs.dependency-type",
                dependencyTypes.map((type) => dependencyTypeValues[type]),
              ),
              // A maintainer change is a supply-chain risk signal, so a human should look.
              "steps.metadata.outputs.maintainer-changes != 'true'",
            ]),
            run: `gh pr merge --auto --${mergeMethod} "$PR_URL"`,
            env: prEnv,
          },
          ...(policy.review === undefined
            ? []
            : [
                {
                  name: "Request a review from this week's reviewer",
                  // Only when the PR wasn't auto-merged, i.e. it needs a person.
                  if: "steps.auto-merge.outcome == 'skipped'",
                  run: reviewerScript,
                  env: {
                    // Usernames are validated (letters, digits, hyphens), so they're safe in shell.
                    REVIEWERS: policy.review.rotation.join(" "),
                    PR_CREATED_AT: "${{ github.event.pull_request.created_at }}",
                    ...prEnv,
                  },
                },
              ]),
        ],
      },
    },
  });
  doc.commentBefore = header;

  const uses = doc.getIn(["jobs", "auto-merge", "steps", 0, "uses"], true);
  if (isScalar(uses)) uses.comment = ` ${fetchMetadata.version}`;

  return doc.toString({ lineWidth: 0 });
}

function anyOf(output: string, values: string[]): string {
  const comparisons = values.map((value) => `${output} == '${value}'`);
  return comparisons.length === 1 ? comparisons[0]! : `(${comparisons.join(" || ")})`;
}

function allOf(conditions: string[]): string {
  return conditions.join(" && ");
}
